#!/usr/bin/env python3

import curses


def main(stdscr):
    curses.use_default_colors()  # https://stackoverflow.com/a/44015131
    for i in range(1, 8):
        # black background, primary colors foreground
        curses.init_pair(i, i, curses.COLOR_BLACK)
        msg = "Color Number" + str(i) + "\n"
        stdscr.addstr(msg, curses.color_pair(i))

        # primary colors background, white foreground
        curses.init_pair(i + 7, curses.COLOR_WHITE, i)
        msg = "Color Number" + str(i + 7) + "\n"
        stdscr.addstr(msg, curses.color_pair(i + 7))

        # primary colors background, black foreground
        curses.init_pair(i + 14, curses.COLOR_BLACK, i)
        msg = "Color Number" + str(i + 14) + "\n"
        stdscr.addstr(msg, curses.color_pair(i + 14))
    stdscr.getch()


curses.wrapper(main)
