#!/usr/bin/env bash

VOICES=($(say -v ? | awk {'print $1'}))

for v in "${VOICES[@]}"; do
    [ -z "$msg" ] && msg="Hello, my name is $v." || msg="$1"
    title="${msg%% *}"
    osascript -e 'display notification "'"$msg"'" with title "'"$title"'"'
    osascript -e "set Volume 10"
    say -v "$v" "$msg"
done
