#!/usr/bin/env bash

batstat=$(upower -i /org/freedesktop/UPower/devices/battery_BAT0| grep -E "state|to\ full|percentage")

if [ -z $batstat ]; then
    PBAT="/sys/class/power_supply/cw2015-battery"
    batstat=$(printf "$(cat $PBAT/status): $(cat $PBAT/capacity)%%\n")
fi


ratpoison -c "echo $batstat"
