- name: Install & configure Microsoft SQL CLI tools
  hosts: localhost
  connection: local
  become: yes
  tasks:
  - name: Fetching GPG key
    apt_key:
      url: "https://packages.microsoft.com/keys/microsoft.asc"
      state: present
  - name: Adding Microsoft sources list
    apt_repository:
      repo: deb [arch=amd64] https://packages.microsoft.com/{{ansible_distribution|lower}}/{{ansible_distribution_version}}/prod {{ansible_distribution_release}} main
      state: present
      filename: mssql
      update_cache: yes
  - name: Installing MSSQL tools and development headers
    apt:
      pkg:
        - msodbcsql17 # apt-cache depends mssql-tools
        - mssql-tools
        - unixodbc-dev
      state:
        present
      update_cache: yes
    environment:
      ACCEPT_EULA: "Y"
  - name: Linking MSSQL tools to /usr/local/bin
    shell: ln -fs /opt/mssql-tools/bin/* /usr/local/bin
    args:
      warn: false
