- name: Install Docker CE
  hosts: localhost
  connection: local
  become: yes
  tasks:
  - name: Install packages to allow apt to use a repository over HTTPS
    apt:
      pkg:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg2
        - software-properties-common
      state: present
      update_cache: yes
  - name: Fetching Docker GPG key
    apt_key:
      url: "https://download.docker.com/linux/debian/gpg"
      state: present
  - name: Adding Docker sources list
    apt_repository:
      repo: deb https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
      state: present
      filename: docker
      update_cache: yes
  - name: Installing Docker CE
    apt:
      pkg:
        - docker-ce
        - docker-ce-cli
        - containerd.io
      state:
        present
  - name: Add user to docker group
    user:
      name: "{{ ansible_user_id }}"
      groups: docker,lxd,sudo
      append: yes
