- name: Install Azure CLI
  hosts: localhost
  connection: local
  become: yes
  tasks:
  - name: Install packages to allow apt to use a repository over HTTPS
    apt:
      pkg:
        - curl
        - apt-transport-https
        - lsb-release
        - ca-certificates
        - gnupg2
        - software-properties-common
      state: present
      update_cache: yes
  - name: Fetching Microsoft GPG key
    apt_key:
      url: "https://packages.microsoft.com/keys/microsoft.asc"
      state: present
  - name: Adding Microsoft Azure CLI sources list
    apt_repository:
      # repo: deb https://packages.microsoft.com/repos/azure-cli/ {{ ansible_distribution_release }} main
      # repo: deb https://packages.microsoft.com/repos/azure-cli/ cosmic main
      repo: deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ cosmic main
      state: present
      filename: azure-cli
      update_cache: yes
  - name: Installing Azure CLI
    apt:
      pkg:
        - azure-cli
      state:
        present
