- name: Install StumpWM from Quicklisp
  hosts: localhost
  vars:
    qlpath: ~/quicklisp.lisp
    slpath: ~/quicklisp/setup.lisp
  tasks:
  - name: Download Quicklisp
    get_url:
      url: https://beta.quicklisp.org/quicklisp.lisp
      dest: '{{qlpath}}'
  - name: Check if Quicklisp already installed
    stat:
      path: ~/quicklisp/setup.lisp
    register: setup
  - name: Install Quicklisp
    shell: |
      echo '(quicklisp-quickstart:install)' | sbcl --load {{qlpath}}
      echo '(ql:add-to-init-file)' | sbcl --load {{slpath}}
    when: not setup.stat.exists
  - name: Install Stumpwm
    shell: |
      echo '(ql:quickload :stumpwm)' | sbcl --load {{slpath}}
      echo '(ql:quickload :xembed)' | sbcl --load {{slpath}}
      echo '(ql:quickload :clx-truetype)' | sbcl --load {{slpath}}
      echo '(ql:quickload :swank)' | sbcl --load {{slpath}}
      echo '(ql:quickload :quicklisp-slime-helper)' | sbcl --load {{slpath}}
      echo '(ql:quickload :zpng)' | sbcl --load {{slpath}}
      echo '(ql:update-client)' | sbcl --load {{slpath}}
      echo '(ql:update-dist "quicklisp")' | sbcl --load {{slpath}}
