- name: Install NodeJS using apt
  hosts: localhost
  become: yes
  vars:
    number: "{{version | default('12')}}"
    node_version: "{{'node_' + number + '.x'}}"
  tasks:
  - name: Fetching GPG key
    apt_key:
      url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
      state: present
  - name: Adding NodeSource Repository
    apt_repository:
      repo: deb https://deb.nodesource.com/{{node_version}} {{ansible_distribution_release}} main
      state: present
      filename: nodesource
      update_cache: yes
  - name: Installing NodeJS
    apt:
      pkg:
        - nodejs
      state:
        present
